import os

def generate_fasta(sequence: str, design_id: str) -> str:
    """Generates a standardized FASTA representation."""
    return f">{design_id} | generated by peptideOS synthesis subsystem\n{sequence}\n"

def calculate_physicochemical_profile(sequence: str) -> dict:
    """Calculates basic physicochemical properties to optimize synthesis."""
    hydrophobic_aas = set(['A', 'V', 'I', 'L', 'M', 'F', 'Y', 'W'])
    acidic_aas = set(['D', 'E'])
    basic_aas = set(['R', 'K', 'H'])
    
    hydrophobic_count = sum(1 for aa in sequence if aa in hydrophobic_aas)
    acidic_count = sum(1 for aa in sequence if aa in acidic_aas)
    basic_count = sum(1 for aa in sequence if aa in basic_aas)
    length = len(sequence)
    
    return {
        "length": length,
        "hydrophobicity_ratio": hydrophobic_count / length if length else 0,
        "charge": basic_count - acidic_count,
        "difficult_sequence": hydrophobic_count / length > 0.5 or length > 20
    }

def generate_spps_script(sequence: str, profile: dict, design_id: str) -> str:
    """Generates parameterized solid-phase peptide synthesis scripts."""
    
    # Protecting group strategies based on sequence
    protecting_groups = []
    if 'R' in sequence: protecting_groups.append("Arg(Pbf)")
    if 'C' in sequence: protecting_groups.append("Cys(Trt)")
    if 'D' in sequence or 'E' in sequence: protecting_groups.append("Asp/Glu(OtBu)")
    if 'K' in sequence: protecting_groups.append("Lys(Boc)")
    if 'S' in sequence or 'T' in sequence or 'Y' in sequence: protecting_groups.append("Ser/Thr/Tyr(tBu)")
    if 'H' in sequence: protecting_groups.append("His(Trt)")
    if 'W' in sequence: protecting_groups.append("Trp(Boc)")
    
    pg_str = ", ".join(protecting_groups) if protecting_groups else "Standard Fmoc protecting groups"
    
    # Coupling reagent selection
    if profile["difficult_sequence"]:
        coupling_reagent = "DIC/Oxyma Pure with heating (microwave-assisted)"
        cycle_steps = "Double coupling"
    else:
        coupling_reagent = "HBTU/DIPEA"
        cycle_steps = "Single coupling"
        
    # Purification gradient
    if profile["hydrophobicity_ratio"] > 0.6:
        gradient = "30% to 90% Acetonitrile (0.1% TFA) over 60 mins"
    elif profile["hydrophobicity_ratio"] < 0.3:
        gradient = "0% to 40% Acetonitrile (0.1% TFA) over 45 mins"
    else:
        gradient = "10% to 60% Acetonitrile (0.1% TFA) over 45 mins"

    script = f"""# ==============================================================================
# SPPS PROTOCOL FOR {design_id}
# ==============================================================================
# Sequence: {sequence}
# Profile: Length={profile['length']}, Charge={profile['charge']}, Hydrophobicity={profile['hydrophobicity_ratio']:.2f}
# ==============================================================================

[SYNTHESIS PARAMETERS]
Platform: Automated Microwave Peptide Synthesizer
Resin: Rink Amide MBHA Resin (0.3 - 0.6 mmol/g)
Scale: 0.1 mmol

[PROTECTING GROUPS]
Strategies: {pg_str}

[COUPLING]
Reagents: {coupling_reagent}
Cycles: {cycle_steps}
Deprotection: 20% Piperidine in DMF (2 x 5 mins)

[CLEAVAGE]
Cocktail: TFA/TIS/H2O (95:2.5:2.5) 
Duration: 2 hours

[PURIFICATION]
Method: Preparative RP-HPLC (C18 column)
Gradient: {gradient}
"""
    return script

def generate_analytical_report(design_id: str, sequence: str, efficacy_scores: dict, visualizations: list) -> str:
    """Compiles comprehensive analytical reports embedding predicted efficacy and visualizations."""
    
    vis_str = "\n".join([f"![Simulation Vis]({v})" for v in visualizations])
    
    report = f"""# Analytical Report: {design_id}
## Sequence Information
**Sequence**: `{sequence}`

## Efficacy Scores
- Binding Affinity: {efficacy_scores.get('binding_affinity', 'N/A')} kcal/mol
- Stability: {efficacy_scores.get('stability', 'N/A')} %
- Therapeutic Index: {efficacy_scores.get('therapeutic_index', 'N/A')}

## Exportable Visualizations
{vis_str}

## Notes
Generated by peptideOS Synthesis Subsystem.
"""
    return report

def generate_python_template(design_id: str, sequence: str) -> str:
    """Generates modular Python code templates for users to extend analyses locally."""
    template = f'''"""
Local Analysis Template for Peptide {design_id}
Sequence: {sequence}

This script uses established bioinformatics libraries (Biopython, RDKit)
to extend the analysis generated by peptideOS.
"""

import sys
try:
    from Bio.SeqUtils.ProtParam import ProteinAnalysis
except ImportError:
    print("Please install Biopython: pip install biopython")
    sys.exit(1)

def analyze_peptide(sequence):
    print(f"Analyzing sequence: {{sequence}}")
    analysis = ProteinAnalysis(sequence)
    
    print(f"Molecular Weight: {{analysis.molecular_weight():.2f}} Da")
    print(f"Isoelectric Point (pI): {{analysis.isoelectric_point():.2f}}")
    print(f"Instability Index: {{analysis.instability_index():.2f}}")
    
    # Extinction coefficient at 280 nm
    ext_coef = analysis.extinction_coefficient()
    print(f"Extinction Coefficient: {{ext_coef[0]}} (reduced) / {{ext_coef[1]}} (oxidized)")

if __name__ == "__main__":
    sequence = "{sequence}"
    analyze_peptide(sequence)
'''
    return template
